export const pageContentData = [
  ['about','about_col2img','image','/uploads/about/col2img.png','About Column Image'],
  ['about','about_culture_desc','text','We\'re passionate about music and art and create new opportunities for artists and influencers to showcase their talent. With the support of our partners, we\'re dedicated to promoting and supporting the next generation.','Culture Card Description'],
  ['about','about_culture_title','text','Our Culture','Culture Card Title'],
  ['about','about_img2','image','/uploads/about/abouttwo.svg','About Image 2'],
  ['about','about_img3','image','/uploads/about/aboutthree.svg','About Image 3'],
  ['about','about_img4','image','/uploads/about/aboutfour.svg','About Image 4'],
  ['about','about_mission_desc','text','To celebrate and promote South Asian Arts & Culture on a global stage, dismantling stereotypes, eradicating bias and combating discrimination to empower individuals in their pursuit of passion.','Mission Card Description'],
  ['about','about_mission_title','text','Our Mission','Mission Card Title'],
  ['about','about_support_desc','text','Since our 2006 launch, we are dedicated to supporting talent in Canada and helping them reach new audiences. We\'ve accomplished this by pooling our resources with a variety of partners, including leading brands and government organisations.','Support Card Description'],
  ['about','about_support_title','text','Our Support','Support Card Title'],
  ['about','about_vision_desc','text','To become the leading global platform for South Asian Arts & Culture. We aim to connect artists, creators and audiences from the diverse South Asian diaspora, fostering a profound sense of belonging and mutual appreciation.','Vision Card Description'],
  ['about','about_vision_title','text','Our Vision','Vision Card Title'],
  ['about','hero_label','text','ABOUT US','Hero Label'],
  ['about','hero_line1','text','showing up for','Hero Line 1'],
  ['about','hero_line2','text','20 years','Hero Line 2'],
  ['artists','featured_img1','image','/uploads/artists/featured1.png','Featured Artist 1'],
  ['artists','featured_img2','image','/uploads/artists/featured2.png','Featured Artist 2'],
  ['artists','featured_img3','image','/uploads/artists/featured3.png','Featured Artist 3'],
  ['artists','hero_image','image','/uploads/artists/hero.png','Hero Background Image'],
  ['artists','hero_line1','text','OUR','Hero Line 1'],
  ['artists','hero_line2','text','ARTISTS','Hero Line 2'],
  ['artists','hero_subtitle','text','LET\'S SHOW UP, CONNECT AND GROW PERFORMANCES','Hero Subtitle'],
  ['community','hero_line1','text','Our','Hero Line 1'],
  ['community','hero_line2','text','Community','Hero Line 2'],
  ['community','hero_subtitle','text','More than a festival. A year-round movement.','Hero Subtitle'],
  ['community','hero_subtitle2','text','But also go through our...','Hero Subtitle Line 2'],
  ['community','open_mic_btn','text','Open Mic','Open Mic Button Text'],
  ['community','sofa_btn','text','Sofa Sessions','Sofa Sessions Button Text'],
  ['concerts','artist_form_bg','image','/uploads/concerts/artistform_bg.png','Artist Form Background'],
  ['concerts','artist_signup_btn','text','ARTIST SIGN UP','Artist Signup Button Text'],
  ['concerts','day0_date','text','JUNE 18','Day 0 Date (Thursday Kick-Off)'],
  ['concerts','day0_description','text','The 20th Anniversary kick-off — an evening showcase exploring the roots and reach of South Asian music across the globe. A celebration of the sounds, stories, and artists that built the blueprint.','Day 0 Description'],
  ['concerts','day0_label','text','LAUNCH NIGHT','Day 0 Label'],
  ['concerts','day0_time','text','7:00PM – 11:00PM','Day 0 Time'],
  ['concerts','day0_title','text','THE BLUEPRINT: HOW SOUTH ASIAN SOUND SHAPED GLOBAL SOUNDS','Day 0 Title'],
  ['concerts','day1_date','text','JUNE 19','Day 1 Date'],
  ['concerts','day1_description','text','A free public event highlighting artists shaped by South Asian roots and global influence. Expect high-energy performances, cross-genre collaborations, and a crowd that reflects the diversity of Toronto itself.','Day 1 Description'],
  ['concerts','day1_label','text','DAY 02','Day 1 Label'],
  ['concerts','day1_time','text','5:00PM – 11:00PM','Day 1 Time'],
  ['concerts','day1_title','text','MULTICULTURAL MUSIC CELEBRATION','Day 1 Title'],
  ['concerts','day2_date','text','JUNE 20','Day 2 Date'],
  ['concerts','day2_description','text','12 hours of free, family-friendly music and dance — showcasing Canadian and international artists performing everything from Bollywood favourites and Punjabi bangers to Hip Hop, Dance, and Pop.','Day 2 Description'],
  ['concerts','day2_label','text','DAY 03','Day 2 Label'],
  ['concerts','day2_time','text','11:00AM – 11:00PM','Day 2 Time'],
  ['concerts','day2_title','text','FOOD VENDORS, BRAND ACTIVATIONS','Day 2 Title'],
  ['concerts','hero_line1','text','THE','Hero Title Line 1'],
  ['concerts','hero_line2','text','CONCERT','Hero Title Line 2'],
  ['concerts','hero_subtitle','text','LIVE MUSIC. SHARED ENERGY. REAL CONNECTION.','Hero Subtitle'],
  ['concerts','hero_taglines','text','THREE DAYS.\nONE COMMUNITY.\nCOUNTLESS MOMENTS.','Hero Taglines (one per line)'],
  ['concerts','hero_year','text','2026','Hero Year'],
  ['concerts','volunteer_btn','text','VOLUNTEER','Volunteer Button Text'],
  ['concerts','volunteer_form_bg','image','/uploads/concerts/volunteer_bg.png','Volunteer Form Background'],
  ['volunteersignup','hero_title','text','VOLUNTEER 2026','Page Title'],
  ['volunteersignup','hero_subtitle','text','Please find here the volunteer submission for 2026 desifest','Page Subtitle'],
  ['volunteersignup','hero_bg','image','/uploads/concerts/volunteer_bg.png','Hero Background Image'],
  ['home','artist_img1','image','/uploads/home/artist1.png','Artists Carousel Image 1'],
  ['home','artist_img2','image','/uploads/home/artist2.png','Artists Carousel Image 2'],
  ['home','artist_img3','image','/uploads/home/artist3.png','Artists Carousel Image 3'],
  ['home','artists_section_title','text','Artists','Artists Section Title'],
  ['home','blog_section_title','text','BLOGS & MEDIA','Blog Section Title'],
  ['home','community_card1_title','text','Year Round Program','Community Card 1 Title'],
  ['home','community_card2_title','text','Open Mic','Community Card 2 Title'],
  ['home','community_card3_title','text','Sofa Sessions','Community Card 3 Title'],
  ['home','community_img1','image','/uploads/home/community1.png','Community Image 1'],
  ['home','community_img2','image','/uploads/home/community2.png','Community Image 2'],
  ['home','community_img3','image','/uploads/home/community3.png','Community Image 3'],
  ['home','community_section_title','text','Community','Community Section Title'],
  ['home','contact_bg_desktop','image','/uploads/home/contact_bg.png','Contact Background (Desktop)'],
  ['home','contact_bg_mobile','image','/uploads/home/contact_bg_mobile.png','Contact Background (Mobile)'],
  ['home','contact_heading','text','Get In Touch','Contact Section Heading'],
  ['home','contact_subtitle','text','Have questions, collaboration ideas, or feedback? We\'d love to hear from you.','Contact Subtitle'],
  ['home','govt_logo1','image','/uploads/sponsors/govt1.png','Government Logo 1 (Ontario Trillium)'],
  ['home','govt_logo2','image','/uploads/sponsors/govt2.png','Government Logo 2 (Ontario Creates)'],
  ['home','govt_logo3','image','/uploads/sponsors/govt3.png','Government Logo 3 (Factor)'],
  ['home','govt_logo4','image','/uploads/sponsors/govt4.png','Government Logo 4 (Toronto Arts)'],
  ['home','govt_logo5','image','/uploads/sponsors/govt5.png','Government Logo 5 (City of Toronto)'],
  ['home','govt_logo6','image','/uploads/sponsors/govt6.png','Government Logo 6 (Canada)'],
  ['home','govt_support_title','text','Government Support','Government Support Title'],
  ['home','hero_anniversary','text','20th Anniversary','Anniversary Text'],
  ['home','hero_arrow_image','image','/uploads/home/arrow.png','Hero Arrow Image'],
  ['home','hero_artist_image','image','/uploads/home/artist.png','Hero Artist Image'],
  ['home','hero_cta_btn','text','BUY TICKETS','Hero CTA Button Text'],
  ['home','hero_date','text','June 18 – 20','Event Date'],
  ['home','hero_description','text','Canada\'s largest South Asian music and arts festival—uniting generations, genres, and voices on one iconic stage.','Hero Description'],
  ['home','hero_line1','text','Where South','Hero Line 1'],
  ['home','hero_line2','text','Asian Culture','Hero Line 2'],
  ['home','hero_line3','text','Meets the World.','Hero Line 3'],
  ['home','hero_location','text','Sankofa Square, Canada','Event Location'],
  ['home','hero_year','text','2026','Event Year'],
  ['home','home_background_2','image','/uploads/home/background_2.png','Artists Section Background'],
  ['home','media_bg','image','/uploads/home/media_bg.png','Blog & Media Background'],
  ['home','partner_logo1','image','/uploads/sponsors/partner1.png','Partner Logo 1'],
  ['home','partner_logo2','image','/uploads/sponsors/partner2.png','Partner Logo 2'],
  ['home','partner_logo3','image','/uploads/sponsors/partner3.png','Partner Logo 3'],
  ['home','partner_logo4','image','/uploads/sponsors/partner4.png','Partner Logo 4'],
  ['home','partner_logo5','image','/uploads/sponsors/partner5.png','Partner Logo 5'],
  ['home','presenting_logo1','image','/uploads/sponsors/presenting1.png','Presenting Sponsor Logo'],
  ['home','shop_img1','image','/uploads/shop/shop1.png','Shop Product 1'],
  ['home','shop_img2','image','/uploads/shop/shop2.png','Shop Product 2'],
  ['home','shop_img3','image','/uploads/shop/shop3.png','Shop Product 3'],
  ['home','shop_img4','image','/uploads/shop/shop4.png','Shop Product 4'],
  ['home','shop_img5','image','/uploads/shop/shop5.png','Shop Product 5'],
  ['home','shop_title','text','SHOP','Shop Section Title'],
  ['home','stat1_label','text','ANNUAL ATTENDEES','Stat 1 Label'],
  ['home','stat1_value','text','150K+','Stat 1 Value'],
  ['home','stat2_label','text','COMMUNITY ARTISTS','Stat 2 Label'],
  ['home','stat2_value','text','1200+','Stat 2 Value'],
  ['home','stat3_label','text','FUNDING GENERATED','Stat 3 Label'],
  ['home','stat3_value','text','3M','Stat 3 Value'],
  ['home','stat4_label','text','CONTENT','Stat 4 Label'],
  ['home','stat4_value','text','1000HR+','Stat 4 Value'],
  ['home','hero_cta_explore','text','Explore','Hero CTA Line 1'],
  ['home','hero_cta_join','text','Join','Hero CTA Line 2'],
  ['home','hero_cta_enjoy','text','Enjoy','Hero CTA Line 3'],
  ['home','partner_support_title','text','Partners & Sponsors','Partners & Sponsors Section Title'],
  ['home','presenting_sponsor_title','text','presenting sponsor','Presenting Sponsor Section Title'],
  ['home','marquee_text1','text','Canada\'s #1 South Asian music festival · Toronto\'s iconic Sankofa Square ·','Marquee Ribbon Text 1'],
  ['home','marquee_text2','text','Toronto\'s iconic Sankofa Square · Canada\'s #1 South Asian music festival ·','Marquee Ribbon Text 2'],
  ['home','animation_video_url','text','czf4UcWwEio','Homepage Background Video URL (YouTube ID or URL)'],
  ['home','shop_product1_title','text','DESIFEST Unisex Windbreaker','Shop Product 1 Title'],
  ['home','shop_product1_price','text','30.00','Shop Product 1 Price'],
  ['home','shop_product1_link','text','/shop/windbreaker','Shop Product 1 Link'],
  ['home','shop_product2_title','text','Desifest Hoodie Blue','Shop Product 2 Title'],
  ['home','shop_product2_price','text','29.00','Shop Product 2 Price'],
  ['home','shop_product2_link','text','/shop/hoodie-blue','Shop Product 2 Link'],
  ['home','shop_product3_title','text','Desifest Hoodie Black','Shop Product 3 Title'],
  ['home','shop_product3_price','text','29.00','Shop Product 3 Price'],
  ['home','shop_product3_link','text','/shop/hoodie-black','Shop Product 3 Link'],
  ['home','shop_product4_title','text','Desifest Vintage Cotton Twill Cap','Shop Product 4 Title'],
  ['home','shop_product4_price','text','25.00','Shop Product 4 Price'],
  ['home','shop_product4_link','text','/shop/vintage-cap','Shop Product 4 Link'],
  ['home','shop_product5_title','text','Organic Ribbed Beanie','Shop Product 5 Title'],
  ['home','shop_product5_price','text','21.00','Shop Product 5 Price'],
  ['home','shop_product5_link','text','/shop/vintage-cap','Shop Product 5 Link'],
  ['home','shop_viewall_text','text','VIEW ALL','Shop View All Button Text'],
  ['home','shop_visible','text','false','Show Shop Section (true/false)'],
  ['sponsorship','video1_url','text','CPhw-lFpLsE','Main Sponsorship Video URL (YouTube ID or URL)'],
  ['sponsorship','calendar_url','text','https://calendar.google.com/calendar/appointments/schedules/AcZssZ1OOyvXelALA3nJXmI2XrqH4gIwUoImjaGSh6IciGamjwoU_LzoJKUuxoZm_qEQODrI2hfaFQk1?gv=true','Google Calendar Appointment URL'],
  ['sofa-sessions','youtube_url','text','https://www.youtube.com/embed/Y02aT2YSD00?autoplay=1&mute=1&controls=1&rel=0','YouTube Video Embed URL'],
  ['media','boost_bg','image','/uploads/media/bwbg.png','Boost Section Background'],
  ['media','boost_img1','image','/uploads/media/boost1.png','Boost Image 1'],
  ['media','boost_img2','image','/uploads/media/boost2.png','Boost Image 2'],
  ['media','boost_img3','image','/uploads/media/boost3.png','Boost Image 3'],
  ['media','boost_img4','image','/uploads/media/boost4.png','Boost Image 4'],
  ['media','contact1_designation','text','DESIGNATION','Contact 1 Designation'],
  ['media','contact1_email','text','abcdesifest@gmail.com','Contact 1 Email'],
  ['media','contact1_name','text','PERSON\'S NAME','Contact 1 Name'],
  ['media','contact1_phone','text','+1234567890','Contact 1 Phone'],
  ['media','contact2_designation','text','DESIGNATION','Contact 2 Designation'],
  ['media','contact2_email','text','abcdesifest@gmail.com','Contact 2 Email'],
  ['media','contact2_name','text','PERSON\'S NAME','Contact 2 Name'],
  ['media','contact2_phone','text','+1234567890','Contact 2 Phone'],
  ['media','contact3_designation','text','DESIGNATION','Contact 3 Designation'],
  ['media','contact3_email','text','abcdesifest@gmail.com','Contact 3 Email'],
  ['media','contact3_name','text','PERSON\'S NAME','Contact 3 Name'],
  ['media','contact3_phone','text','+1234567890','Contact 3 Phone'],
  ['media','contacts_heading','text','PEOPLE OF CONTACT','Contacts Section Heading'],
  ['media','hero_title','text','MEDIA & PRESS','Hero Title'],
  ['media','hero_top_text','text','The Story Behind The Stage','Hero Top Text'],
  ['media','logos_title','text','OUR OFFICIAL LOGOS','Official Logos Section Title'],
  ['media','media_bw_logo','image','/uploads/media/bw.svg','B&W Logo'],
  ['media','media_color_logo','image','/uploads/media/color.svg','Color Logo'],
  ['media','mission_description','text','To become the leading global platform for South Asian Arts & Culture. We aim to connect artists, creators and audiences from the diverse South Asian diaspora, fostering a profound sense of belonging and mutual appreciation.','Mission Description'],
  ['media','mission_heading_line1','text','Where South Asian Artists Meet the World','Mission Heading'],
  ['media','mission_label','text','Mission Statement','Mission Label'],
  ['media','mission_stat1_label','text','FACEBOOK FANS','Mission Stat 1 Label'],
  ['media','mission_stat1_value','text','13K+','Mission Stat 1 Value'],
  ['media','mission_stat2_label','text','INSTAGRAM FANS','Mission Stat 2 Label'],
  ['media','mission_stat2_value','text','28K+','Mission Stat 2 Value'],
  ['media','mission_stat3_label','text','TOTAL IMPRESSIONS','Mission Stat 3 Label'],
  ['media','mission_stat3_value','text','45M+','Mission Stat 3 Value'],
  ['media','mission_stat4_label','text','FESTIVAL ATTENDANCE','Mission Stat 4 Label'],
  ['media','mission_stat4_value','text','65K+','Mission Stat 4 Value'],
  ['media','press_details_text','text','Get Our Press Details Here!','Press Details Text'],
  ['openmic','featured_img1','image','/uploads/openmic/featured1.png','Featured Artist 1'],
  ['openmic','featured_img10','image','/uploads/openmic/featured10.png','Featured Artist 10'],
  ['openmic','featured_img11','image','/uploads/openmic/featured11.png','Featured Artist 11'],
  ['openmic','featured_img12','image','/uploads/openmic/featured12.png','Featured Artist 12'],
  ['openmic','featured_img13','image','/uploads/openmic/featured13.png','Featured Artist 13'],
  ['openmic','featured_img14','image','/uploads/openmic/featured14.png','Featured Artist 14'],
  ['openmic','featured_img15','image','/uploads/openmic/featured15.png','Featured Artist 15'],
  ['openmic','featured_img16','image','/uploads/openmic/featured16.png','Featured Artist 16'],
  ['openmic','featured_img2','image','/uploads/openmic/featured2.png','Featured Artist 2'],
  ['openmic','featured_img3','image','/uploads/openmic/featured3.png','Featured Artist 3'],
  ['openmic','featured_img4','image','/uploads/openmic/featured4.png','Featured Artist 4'],
  ['openmic','featured_img5','image','/uploads/openmic/featured5.png','Featured Artist 5'],
  ['openmic','featured_img6','image','/uploads/openmic/featured6.png','Featured Artist 6'],
  ['openmic','featured_img7','image','/uploads/openmic/featured7.png','Featured Artist 7'],
  ['openmic','featured_img8','image','/uploads/openmic/featured8.png','Featured Artist 8'],
  ['openmic','featured_img9','image','/uploads/openmic/featured9.png','Featured Artist 9'],
  ['openmic','featured_section_title','text','Featured artists','Featured Artists Section Title'],
  ['openmic','hero_image','image','/uploads/openmic/hero.png','Hero Background Image'],
  ['openmic','hero_subtitle','text','WHERE NEW VOICES TAKE THEIR FIRST STEP','Hero Subtitle'],
  ['openmic','hero_title','text','OPEN MIC','Hero Title'],
  ['openmic','seasons_section_title','text','SEASONS AND PLACES','Seasons Section Title'],
  ['openmic','session1_handle','text','SEASON 3','Session 1 Handle'],
  ['openmic','session1_name','text','DURHAM','Session 1 Name'],
  ['openmic','session2_handle','text','SEASON 3','Session 2 Handle'],
  ['openmic','session2_name','text','Lahore Tikka House','Session 2 Name'],
  ['openmic','session3_handle','text','SEASON 3','Session 3 Handle'],
  ['openmic','session3_name','text','TORONTO','Session 3 Name'],
  ['openmic','session_img1','image','/uploads/openmic/session1.jpg','Session Image 1'],
  ['openmic','session_img2','image','/uploads/openmic/session2.jpg','Session Image 2'],
  ['openmic','session_img3','image','/uploads/openmic/session3.jpg','Session Image 3'],
  ['press-kit','download_btn','text','Download Kit','Download Button Text'],
  ['press-kit','hero_subtext','text','Download the full 2026 media kit','Subtext'],
  ['press-kit','hero_title','text','MEDIA KIT','Main Title'],
  ['press-kit','hero_top_heading','text','2026 DESIFEST','Top Heading'],
  ['press-kit','presskit_bg','image','/uploads/presskit/background.png','Press Kit Background'],
  ['sofa-sessions','card1_description','text','Born during the pandemic, DESIFEST Sofa Sessions brought our community together when live performances stopped.','Card 1 Description'],
  ['sofa-sessions','card1_title','text','The beginning','Card 1 Title'],
  ['sofa-sessions','card2_description','text','What began as a simple sofa evolved into a hub for genuine conversations, talent showcases, and the inspiring stories of South Asian artists. We celebrate their journeys and creative paths beyond the spotlight.','Card 2 Description'],
  ['sofa-sessions','card2_title','text','Artist Platform','Card 2 Title'],
  ['sofa-sessions','card3_description','text','This initiative focuses on building community, celebrating culture, and keeping the conversation going. Even when the music pauses, the stories continue to resonate.','Card 3 Description'],
  ['sofa-sessions','card3_title','text','Community & Culture','Card 3 Title'],
  ['sponsorship','description','text','We are excited to be back for our 18th annual DESIFEST – Toronto\'s award winning South Asian Music Festival. This is a unique and proven marketing opportunity for your brand! Find a time below that work for us to get a on call and explore how you can tap into the power of multicultural marketing with DESIFEST 2024.','Sponsorship Description'],
];

export const blogPostsData = [
  {
    slug: 'desifest-press-release',
    title: 'DESIFEST 2025 "We are Canadian" return...',
    full_title: 'DESIFEST 2025 Returns to Sankofa Square with Bold "We Are Canadian" Vision',
    date: 'May 15, 2025',
    author: 'Sathish Bala',
    category: 'Press Release',
    description: 'DESIFEST 2025 Doubles Down on Canadian South Asian Talent with Bold "We Are Canadian" Return to Sankofa Square...',
    image_url: '/uploads/media/blog-cover-1.png',
    badge: 'FOR IMMEDIATE RELEASE',
    meta: {"type": "Press Release", "location": "Toronto, ON"},
    sections: [{"text":"Canada's largest South Asian music festival returns for its 19th year — stronger, louder, and more proudly Canadian than ever.","type":"intro"},{"text":"DESIFEST returns to Sankofa Square on Saturday, June 14, 2025, continuing its mission of empowering homegrown South Asian artists and reshaping Canada's cultural narrative. After its historic all-Canadian lineup in 2024, this year's edition doubles down on investing in local talent.","type":"paragraph"},{"text":"A National Cultural Moment","type":"heading"},{"text":"Presented by TD Bank Group, the festival runs from 11 AM to 11 PM under the powerful theme \"We Are Canadian.\" In a milestone year where South Asian music earned formal recognition at the JUNO Awards, DESIFEST continues to lead — not just reflecting representation, but actively building the platform.","type":"paragraph"},{"text":"19 Years of Impact","type":"heading"},{"text":"Since 2006, DESIFEST has supported over 1,000 artists, invested more than $3 million into cultural development, and hosted over 60,000 attendees annually. In 2024 alone, the festival reached over 45 million people digitally.","type":"paragraph"},{"text":"More Than Music","type":"heading"},{"text":"With curated stages spanning Bollywood, Punjabi, Bangla, Carnatic Fusion, Hip Hop, and R&B, DESIFEST is more than a music festival — it's a movement. The event features 20+ food vendors, interactive exhibits, kids' zones, and inclusive spaces for all ages.","type":"paragraph"},{"name":"Sathish Bala","role":"Founder & CEO, DESIFEST","type":"contact-card","email":"sbala@desifest.ca","phone":"416-302-9321","website":"www.desifest.ca","location":"Sankofa Square, Toronto"}],
    social_links: {"twitter":"https://x.com/intent/post?text=DESIFEST%202025%20Returns%20to%20Sankofa%20Square&url=https%3A%2F%2Fdesifest.ca%2Fdesifest-2025%2F","facebook":"https://www.facebook.com/sharer/sharer.php?u=https://desifest.ca/desifest-2025/","linkedin":"https://www.linkedin.com/feed/?shareActive=true&shareUrl=https%3A%2F%2Fdesifest.ca%2Fdesifest-2025%2F"},
    published: true
  },
  {
    slug: 'open-mic-unplugged',
    title: 'Open Mic Unplugged Brings Back...',
    full_title: 'Open Mic Unplugged Brings South Asian Music Back to Gerrard Street',
    date: 'May 17, 2025',
    author: 'Sathish Bala',
    category: 'MUSIC',
    description: 'Open Mic Unplugged Brings South Asian Music Back to the Heart of Gerrard Street May 31...',
    image_url: '/uploads/media/blog-cover-2.png',
    badge: 'FOR IMMEDIATE RELEASE',
    meta: {"type":"MUSIC","location":"Toronto, ON"},
    sections: [{"date":"Saturday, May 31, 2025","time":"7:00 PM – 10:00 PM","type":"event-details","venue":"Lahore Tikka House, Gerrard Street East, Toronto"},{"text":"As part of South Asian Heritage Month, DESIFEST launches a new acoustic concert series rooted in storytelling, culture, and community.","type":"intro"},{"text":"This inaugural edition takes place at one of Toronto's most iconic venues — Lahore Tikka House. More than a restaurant, it stands as a cultural landmark in Little India, symbolizing resilience and belonging.","type":"paragraph"},{"text":"\"This isn't just about a show — it's about honouring our roots, elevating emerging voices, and making sure culture lives in our neighborhoods.\"","type":"quote","attribution":"Sathish Bala"},{"text":"The Experience","type":"heading"},{"text":"Curated by Dee Devan and hosted by SatsB, Open Mic Unplugged features Bollywood ballads, Tamil acoustic sets, Indie Fusion, R&B, and spoken word — spotlighting artists who have grown through DESIFEST's open mic ecosystem.","type":"paragraph"},{"text":"Food & Atmosphere","type":"heading"},{"text":"Lahore Tikka House will serve a special curated menu including:","type":"paragraph"},{"type":"list","items":["Chicken & Paneer Tikka","Fresh naan & Tandoori platters","Samosas, Pakoras & Street-style snacks","Mango lassi, Chai & Classic desserts"]},{"text":"Tickets","type":"heading"},{"type":"pricing","tiers":[{"label":"Early Bird","price":"$20"},{"label":"General","price":"$25"},{"label":"At the Door","price":"$35"}]},{"text":"Limited seating available — reserve early to guarantee your spot.","type":"paragraph","italic":true},{"text":"About Gerrard India Bazaar","type":"heading"},{"text":"Known as \"Little India,\" Gerrard India Bazaar remains one of Toronto's most vibrant cultural corridors — a space where South Asian identity, food, art, and tradition thrive.","type":"paragraph"}],
    social_links: {"twitter":"#","facebook":"#","linkedin":"#"},
    published: true
  },
  {
    slug: 'a-typographic-legend',
    title: 'A Typographic Legend: Jan Middendorp',
    full_title: 'A Typographic Legend: Jan Middendorp',
    date: 'January 7, 2024',
    author: 'andrealeksen',
    category: 'Tribute',
    description: 'Jan Middendorp (4/9/56–12/8/23) contributed an incredible wealth of knowledge to the field of typography...',
    image_url: '/uploads/media/blog-cover-3.png',
    badge: 'In Memoriam',
    meta: {"type":"Tribute"},
    sections: [{"text":"Jan Middendorp (1956–2023) leaves behind a legacy that shaped modern typography and touched countless designers around the world.","type":"intro"},{"text":"I met Jan at my first TypeCon conference in Milwaukee in 2012. He quickly became one of my earliest mentors — offering business advice, type critiques, and introductions that opened doors across the global typography community.","type":"paragraph"},{"text":"A Teacher & Author","type":"heading"},{"text":"Jan authored numerous typography books that were not only rich in knowledge, but beautifully designed and written with warmth and accessibility. His textbook \"Shaping Text\" became a staple in my Intro to Typography courses — thoughtful, thorough, and filled with inviting chapter titles like \"Seducing with Type.\"","type":"paragraph"},{"text":"Beyond the Conference Stage","type":"heading"},{"text":"Conferences were where ideas were exchanged — but the real magic often happened afterward. Whether it was paella on a beach in Barcelona, dancing in Amsterdam, or rooftop gatherings across Europe, Jan was always present — thoughtful, observant, and quietly joyful.","type":"paragraph"},{"text":"A bright light in the international type community has dimmed — but the influence, generosity, and knowledge he shared will endure.","type":"quote"},{"text":"Our community is small, but deeply connected. Jan's impact on my professional journey — and personal life — is immeasurable. May your memory live on, dear Jan.","type":"paragraph"},{"text":"Thank you for the mentorship, the wisdom, and the inspiration.","type":"tribute-card","years":"1956 – 2023"}],
    social_links: {"twitter":"https://x.com/intent/post?text=A%20Typographic%20Legend%3A%20Jan%20Middendorp&url=https%3A%2F%2Fdesifest.ca%2Fa-typographic-legend-jan-middendorp%2F","facebook":"https://www.facebook.com/sharer/sharer.php?u=https://desifest.ca/a-typographic-legend-jan-middendorp/","linkedin":"https://www.linkedin.com/feed/?shareActive=true&shareUrl=https%3A%2F%2Fdesifest.ca%2Fa-typographic-legend-jan-middendorp%2F"},
    published: true
  },
  {
    slug: 'three-more-years-one-shared-commitment-to-culture',
    title: 'Three More Years. One Shared Commitment to Culture.',
    full_title: 'Three More Years. One Shared Commitment to Culture.',
    date: 'February 24, 2026',
    author: 'DESIFEST',
    category: 'Press',
    description: 'There are moments in a festival\'s journey that feel bigger than programming.',
    image_url: '/uploads/media/blog-cover-4.png',
    badge: 'FOR IMMEDIATE RELEASE',
    meta: {},
    sections: [{"type":"intro","text":"There are moments in a festival's journey that feel bigger than programming."},{"type":"paragraph","text":"Today is one of them."},{"type":"paragraph","text":"As DESIFEST enters its 20th year, we are proud to announce a renewed three year partnership with TD Bank, extending their continued support of our platform and the South Asian creative community across Canada."},{"type":"paragraph","text":"For two decades, DESIFEST has been built on belief. Belief that South Asian artists deserve major stages. Belief that families deserve spaces where heritage and identity are celebrated openly. Belief that culture is not a niche audience. It is infrastructure."},{"type":"paragraph","text":"Partnerships like this do not happen overnight. They are earned over time through consistency, credibility, and community trust."},{"type":"paragraph","text":"TD has been part of our journey not just as a logo on a stage, but as a partner who understands that culture drives connection, belonging, and long term brand equity."},{"type":"heading","text":"WHY THIS MATTERS"},{"type":"paragraph","text":"Arts and culture platforms often operate in a delicate ecosystem. Government funding looks for private sector validation. Corporate sponsors look for measurable impact. Meanwhile, communities look for places to gather and see themselves reflected."},{"type":"paragraph","text":"A multi year commitment sends a different message."},{"type":"paragraph","text":"It says culture is not a one year experiment."},{"type":"paragraph","text":"It says community building requires continuity."},{"type":"paragraph","text":"It says long term investment creates long term impact."},{"type":"paragraph","text":"Over the next three years, this partnership will support:"},{"type":"list","items":["Canadian South Asian artists performing on a national stage","Multi generational programming in the heart of downtown Toronto","Opportunities for students, newcomers, and families to connect through music","Experiential engagement that reflects the diversity of our city"]},{"type":"paragraph","text":"TD's continued support reinforces that DESIFEST is not just an event. It is part of Toronto's cultural fabric."},{"type":"heading","text":"TWENTY YEARS STRONG"},{"type":"paragraph","text":"In 2026, DESIFEST celebrates 20 years at Sankofa Square. From our earliest stages to welcoming over 100,000 attendees annually, we have grown alongside the community we serve."},{"type":"paragraph","text":"The South Asian population in Canada continues to expand in influence, entrepreneurship, education, and cultural leadership. Platforms like DESIFEST create the spaces where that identity is expressed publicly and proudly."},{"type":"paragraph","text":"To have a partner like TD stand with us for another three years affirms the value of that work."},{"type":"heading","text":"GRATITUDE AND RESPONSIBILITY"},{"type":"paragraph","text":"We are grateful for the trust."},{"type":"paragraph","text":"And we take it seriously."},{"type":"paragraph","text":"This renewed partnership allows us to think bigger, plan further ahead, and deepen the experiences we create for artists, families, and audiences."},{"type":"paragraph","text":"Culture survives because people show up."},{"type":"paragraph","text":"Culture thrives because partners invest."},{"type":"paragraph","text":"To TD Bank, thank you for believing in the stage, the artists, and the community."},{"type":"paragraph","text":"We look forward to building the next chapter together."}],
    social_links: {},
    published: true
  }
];
